local name, Fugg = ...;

Fugg.dolan_patterns = {
    "what would dolan do",
    "unproffesional",
    "motherfucker",
    "rainbow dash",
    "anniversary",
    "chill pills",
    "every thing",
    "examination",
    "linkin park",
    "chill pill",
    "conspiracy",
    "don't know",
    "every time",
    "everything",
    "girlfriend",
    "godbrother",
    "masterbate",
    "production",
    "unexpected",
    "beautiful",
    "chocolade",
    "cigarette",
    "copyright",
    "delicious",
    "everytime",
    "gentlemen",
    "happening",
    "inception",
    "mcdonalds",
    "meanwhile",
    "minecraft",
    "modernest",
    "por favor",
    "rick roll",
    "something",
    "spiderman",
    "terrorist",
    "thank you",
    "therapist",
    "virginity",
    "wallpaper",
    "what's up",
    "actually",
    "addicted",
    "allergic",
    "avengers",
    "birthday",
    "bumholes",
    "business",
    "cupcakes",
    "drinking",
    "everyone",
    "eyeballs",
    "gasoline",
    "going to",
    "happened",
    "happiest",
    "in a car",
    "medicine",
    "moralfag",
    "quickest",
    "skrillex",
    "somebody",
    "stranger",
    "suitcase",
    "tsunamis",
    "twilight",
    "ultimate",
    "whatever",
    "yourself",
    "america",
    "awesome",
    "bastard",
    "because",
    "blocked",
    "brother",
    "builder",
    "buttsex",
    "checkup",
    "chicken",
    "come on",
    "cooking",
    "created",
    "cupcake",
    "doesn't",
    "dollars",
    "finally",
    "fucking",
    "haven't",
    "hipster",
    "jewelry",
    "karagon",
    "kingdom",
    "married",
    "mexican",
    "monster",
    "monthly",
    "muscles",
    "niggers",
    "nothing",
    "outside",
    "peanuts",
    "picture",
    "someone",
    "sucking",
    "teacher",
    "therapy",
    "titties",
    "toaster",
    "trolled",
    "tsunami",
    "wearing",
    "website",
    "windows",
    "without",
    "accept",
    "addict",
    "animal",
    "ashley",
    "batman",
    "before",
    "better",
    "bobman",
    "broken",
    "cancer",
    "candle",
    "carrot",
    "center",
    "change",
    "chrome",
    "contex",
    "crying",
    "dammit",
    "dinner",
    "disney",
    "divide",
    "doctor",
    "dollar",
    "donald",
    "double",
    "eleven",
    "entire",
    "faggot",
    "famous",
    "finger",
    "flower",
    "forgot",
    "friend",
    "garden",
    "hating",
    "hijack",
    "matter",
    "minute",
    "modern",
    "moment",
    "mister",
    "muslim",
    "nature",
    "nigger",
    "number",
    "people",
    "planet",
    "please",
    "police",
    "pretty",
    "rarity",
    "really",
    "scared",
    "scooby",
    "second",
    "secret",
    "seeing",
    "shower",
    "skiing",
    "sniper",
    "stupid",
    "thanks",
    "though",
    "trying",
    "virgin",
    "we are",
    "wizard",
    "about",
    "above",
    "after",
    "again",
    "anger",
    "april",
    "bacon",
    "birth",
    "bitch",
    "block",
    "black",
    "blood",
    "boobs",
    "brain",
    "brick",
    "bucks",
    "can't",
    "cause",
    "chuck",
    "clown",
    "couch",
    "could",
    "crash",
    "don't",
    "dream",
    "drunk",
    "enjoy",
    "exist",
    "floor",
    "fools",
    "funny",
    "glory",
    "gonna",
    "goofy",
    "guess",
    "happy",
    "heart",
    "hello",
    "idgaf",
    "idiot",
    "islam",
    "jesus",
    "juice",
    "juicy",
    "later",
    "let's",
    "looks",
    "metal",
    "never",
    "obama",
    "other",
    "party",
    "pluto",
    "power",
    "quick",
    "raped",
    "rocks",
    "satan",
    "shall",
    "share",
    "shirt",
    "sleep",
    "smile",
    "sorry",
    "steak",
    "story",
    "stuck",
    "style",
    "super",
    "taste",
    "testa",
    "there",
    "thing",
    "times",
    "today",
    "trade",
    "trick",
    "truck",
    "uncle",
    "until",
    "venom",
    "wanna",
    "watch",
    "water",
    "we're",
    "women",
    "world",
    "would",
    "wrong",
    "years",
    "anal",
    "anus",
    "bail",
    "beer",
    "blow",
    "boys",
    "busy",
    "cake",
    "cant",
    "care",
    "cash",
    "come",
    "cute",
    "damn",
    "date",
    "dead",
    "eggs",
    "ever",
    "evil",
    "eyes",
    "fire",
    "from",
    "fuck",
    "game",
    "golf",
    "good",
    "guys",
    "hand",
    "hate",
    "have",
    "help",
    "here",
    "high",
    "i am",
    "idea",
    "just",
    "keep",
    "kids",
    "kill",
    "knwo",
    "life",
    "like",
    "lisa",
    "live",
    "long",
    "look",
    "lost",
    "love",
    "make",
    "mona",
    "more",
    "must",
    "nazi",
    "need",
    "next",
    "nice",
    "okay",
    "page",
    "pass",
    "pick",
    "play",
    "plox",
    "rage",
    "rape",
    "read",
    "real",
    "rest",
    "ride",
    "said",
    "seat",
    "send",
    "sexy",
    "shit",
    "shop",
    "show",
    "sick",
    "some",
    "stay",
    "stop",
    "suck",
    "sure",
    "take",
    "tell",
    "than",
    "that",
    "them",
    "then",
    "they",
    "this",
    "till",
    "time",
    "true",
    "turn",
    "type",
    "very",
    "wait",
    "walt",
    "want",
    "wash",
    "well",
    "went",
    "what",
    "will",
    "with",
    "woof",
    "work",
    "year",
    "york",
    "your",
    "all",
    "and",
    "are",
    "bat",
    "bed",
    "bro",
    "can",
    "cat",
    "die",
    "egg",
    "for",
    "gay",
    "gee",
    "get",
    "god",
    "got",
    "guy",
    "how",
    "i'm",
    "idk",
    "lol",
    "may",
    "new",
    "not",
    "now",
    "say",
    "see",
    "sex",
    "smd",
    "sup",
    "the",
    "too",
    "was",
    "why",
    "you",
    "do",
    "he",
    "in",
    "is",
    "it",
    "me",
    "mr",
    "my",
    "of",
    "ok",
    "to",
    "i"
}

Fugg.dolan_replacements = {
    { 'what would dolan does' },
    { 'unprofeshnl' },
    { 'motrfukr', 'motrfuker', 'motrfakr', 'motrfaker', 'mtherfukr', 'mtherfuker', 'mtherfakr', 'mtherfaker' },
    { 'arnbo' },
    { 'anibersary' },
    { 'chilpils' },
    { 'evryting', 'everiting', 'everyting' },
    { 'examnashun' },
    { 'link park' },
    { 'chilpil' },
    { 'cnspaercy' },
    { 'dunno' },
    { 'evrytim' },
    { 'evryting', 'everiting', 'everyting' },
    { 'grilfrend' },
    { 'gdbrthr' },
    { 'fap' },
    { 'prodization' },
    { 'unepecxted' },
    { 'baetuiful' },
    { 'chocolat' },
    { 'cigrete' },
    { 'copyrites' },
    { 'dlishus' },
    { 'evrytim' },
    { 'gntelmen' },
    { 'hapenin' },
    { 'inceptyon' },
    { 'mcdolanz' },
    { 'maenwihle' },
    { 'minkreft' },
    { 'modurnest' },
    { 'prf avor' },
    { 'rix role' },
    { 'sumthn', 'smthn', 'somseng' },
    { 'spooderman', 'spodermn', 'spoodermin', 'spoodey', 'spody' },
    { 'teroras' },
    { 'ty' },
    { 'theerpist' },
    { 'vnrginty' },
    { 'walpeeper', 'walpapr' },
    { 'sup' },
    { 'accualy', 'acuali', 'accually' },
    { 'adikted' },
    { 'allergicc' },
    { 'avengars' },
    { 'byrthdayz', 'burfdy', 'birfday' },
    { 'bumholez' },
    { 'businss', 'biznus' },
    { 'cupcaeks' },
    { 'drinkig' },
    { 'evryon' },
    { 'eyebals' },
    { 'gaseline' },
    { 'gunna', 'gona' },
    { 'hapnd' },
    { 'hapiest' },
    { 'incar' },
    { 'medsin' },
    { 'morelfeg', 'mrlfeg' },
    { 'qiukest' },
    { 'skrix', 'skrlx' },
    { 'soembady', 'sumbudy', 'sumbody', 'sumbdy' },
    { 'strngr' },
    { 'sootcais' },
    { 'tusnamis' },
    { 'twalot' },
    { 'ultimaet' },
    { 'watevur' },
    { 'yurselv' },
    { 'amerika' },
    { 'awsum' },
    { 'besterd' },
    { 'cuz', 'bcuz', 'bcus' },
    { 'blokd' },
    { 'brotr', 'brthr' },
    { 'buildr', 'bulder' },
    { 'bhutt secks' },
    { 'chekup' },
    { 'chikn' },
    { 'cum on' },
    { 'cuking' },
    { 'crated' },
    { 'cupcaek' },
    { 'dsnt' },
    { 'dolars' },
    { 'finully' },
    { 'fakn', 'fakin', 'fukin', 'fukn' },
    { 'havn' },
    { 'hpistr' },
    { 'jewlry' },
    { 'karafap', 'kragon' },
    { 'kendum' },
    { 'marreyd' },
    { 'border jumper' },
    { 'menstr' },
    { 'monfly' },
    { 'msucels' },
    { 'nigurs', 'nigers', 'nigges' },
    { 'nuthng' },
    { 'outsed' },
    { 'peenutz' },
    { 'pishur' },
    { 'sum1' },
    { 'sukn', 'sakin', 'sukin' },
    { 'taechr' },
    { 'thrapy' },
    { 'tittays' },
    { 'toastre' },
    { 'troled', 'trold', 'trolde' },
    { 'tusnami' },
    { 'weerin' },
    { 'websyt' },
    { 'windos' },
    { 'weetout' },
    { 'acept' },
    { 'adikt' },
    { 'animel' },
    { 'sexai bish' },
    { 'btmn' },
    { 'befo', 'bfur', 'befur', 'bfare', 'bfor' },
    { 'bitters' },
    { 'bbmen' },
    { 'boerkn' },
    { 'cansor', 'cansur' },
    { 'cnadl', 'candel' },
    { 'karot' },
    { 'centar' },
    { 'chanj' },
    { 'cohrme' },
    { 'cntex' },
    { 'criyin' },
    { 'demmit' },
    { 'dinnr', 'dner' },
    { 'dosni' },
    { 'deviding' },
    { 'docte' },
    { 'dolar' },
    { 'dolan' },
    { 'duble' },
    { 'elven' },
    { 'entrire' },
    { 'feget', 'faggat', 'fgt' },
    { 'famus' },
    { 'fingor' },
    { 'flowa' },
    { 'frogot' },
    { 'frend', 'flend' },
    { 'gurden' },
    { 'heatin' },
    { 'hijak' },
    { 'maddr' },
    { 'minit', 'minut' },
    { 'modurn' },
    { 'momunt' },
    { 'mistur' },
    { 'mozlem' },
    { 'nateur' },
    { 'nigur', 'niger' },
    { 'nmber' },
    { 'ppl' },
    { 'planut' },
    { 'pls', 'plss', 'plz', 'plx' },
    { 'poleec' },
    { 'prety' },
    { 'rarty' },
    { 'rly', 'relly', 'rely' },
    { 'scraed' },
    { 'skubby' },
    { 'sec' },
    { 'sicret' },
    { 'seein' },
    { 'showr' },
    { 'skeeing' },
    { 'sniepr' },
    { 'stopid', 'stuped', 'stupd' },
    { 'tanks', 'ty' },
    { 'tuff' },
    { 'trieng' },
    { 'vargin' },
    { 'we' },
    { 'wizerd' },
    { 'abt', 'abot' },
    { 'aboev' },
    { 'aftr' },
    { 'egen', 'agen' },
    { 'angr', 'angrey' },
    { 'aprel' },
    { 'bacons' },
    { 'birt', 'brth' },
    { 'betch' },
    { 'blok' },
    { 'bleck', 'blaek' },
    { 'blud' },
    { 'bewbz' },
    { 'brean' },
    { 'brik' },
    { 'bukz' },
    { "ca'nt", 'cant', 'ctan' },
    { 'cuz' },
    { 'chak' },
    { 'clauwn' },
    { 'cuch' },
    { 'cud' },
    { 'crehs' },
    { 'dunt', 'doent', 'dnot' },
    { 'drem' },
    { 'dronk' },
    { 'enjoi', 'njoi' },
    { 'exeest' },
    { 'flour', 'flur' },
    { 'fules' },
    { 'funey', 'fany', 'funnay' },
    { 'glroy' },
    { 'gunna', 'gona' },
    { 'gooby' },
    { 'gess' },
    { 'hapy', 'hapy' },
    { 'hert' },
    { 'hlelo', 'henlo'},
    { 'igaf' },
    { 'idoit', 'edeot', 'ideot' },
    { 'izlam' },
    { 'jizzus', 'jzuz' },
    { 'jewce' },
    { 'joocy' },
    { 'laytor' },
    { 'lest', 'les', 'lez' },
    { 'loks', 'luks' },
    { 'mteal' },
    { 'neer' },
    { 'negropres', 'obama' },
    { 'ohtr' },
    { 'paryt' },
    { 'pruto' },
    { 'pwoer' },
    { 'quik' },
    { 'raeped', 'reaped', 'raepd', 'reapd' },
    { 'racks' },
    { 'saytan' },
    { 'shell' },
    { 'shar' },
    { 'sirht' },
    { 'slep' },
    { 'smiel' },
    { 'sawry' },
    { 'stek' },
    { 'stori' },
    { 'sutck' },
    { 'styel' },
    { 'spuer' },
    { 'tast', 'taest' },
    { 'tsta' },
    { 'ther' },
    { 'thinng' },
    { 'tiems' },
    { 'todei' },
    { 'traed' },
    { 'trik' },
    { 'turk' },
    { 'uncel', 'unecl' },
    { 'til' },
    { 'venam' },
    { 'wan' },
    { 'wacht', 'wacth' },
    { 'woter', 'wtr' },
    { 'we' },
    { 'wmen' },
    { 'wrld', 'wurld', 'wolrd' },
    { 'wud', 'wuld' },
    { 'rong' },
    { 'yrs', 'yaers' },
    { 'anl' },
    { 'anis' },
    { 'belz' },
    { 'bier' },
    { 'blw' },
    { 'bois' },
    { 'busi' },
    { 'kake' },
    { 'ctan' },
    { 'caret' },
    { 'kash' },
    { 'coem' },
    { 'cuet' },
    { 'dayum', 'demn' },
    { 'dayte', 'dait' },
    { 'ded' },
    { 'egs' },
    { 'evur', 'evir' },
    { 'evul', 'evel' },
    { 'eeys' },
    { 'fier' },
    { 'frem' },
    { 'fak', 'faq', 'fk', 'fek', 'feq', 'fuk', 'fck' },
    { 'gaem', 'gaym' },
    { 'gorf' },
    { 'gud' },
    { 'guise' },
    { 'hamd' },
    { 'haet' },
    { 'has', 'haz', 'haev', 'heiv', 'hav' },
    { 'halp' },
    { 'heer', 'hur' },
    { 'hi' },
    { 'im' },
    { 'idia' },
    { 'juts' },
    { 'keip', 'kepe' },
    { 'keds' },
    { 'kel', 'kil' },
    { 'kno' },
    { 'lif', 'liyfe', 'lyfe' },
    { 'leik', 'lyk', 'lik', 'liek' },
    { 'lis' },
    { 'liv' },
    { 'lnog' },
    { 'luk', 'lok' },
    { 'losd' },
    { 'luv' },
    { 'maek', 'mak' },
    { 'muna' },
    { 'mor', 'moar' },
    { 'mus' },
    { 'natzi' },
    { 'nede', 'ned' },
    { 'nex' },
    { 'niec' },
    { 'k' },
    { 'paeg' },
    { 'pas' },
    { 'pik' },
    { 'pley', 'pray' },
    { 'plx' },
    { 'raeg' },
    { 'raep', 'reap' },
    { 'raed', 'red' },
    { 'reel' },
    { 'rast' },
    { 'ried', 'ryde' },
    { 'sayd', 'sed' },
    { 'seet' },
    { 'snd', 'sen' },
    { 'seyx' },
    { 'shet', 'shyt' },
    { 'shopn' },
    { 'shwo' },
    { 'sik' },
    { 'soem', 'sum' },
    { 'sty' },
    { 'stup', 'stap', 'stahp' },
    { 'suk', 'sak', 'sk', 'saq', 'seq', 'sek' },
    { 'shor', 'shur', 'shure', 'suer' },
    { 'taek', 'tak' },
    { 'tael' },
    { 'thans' },
    { 'dat' },
    { 'dem' },
    { 'ten' },
    { 'dey' },
    { 'dis', 'tis' },
    { 'til' },
    { 'tiem' },
    { 'tru', 'trew' },
    { 'tern' },
    { 'tiep' },
    { 'vury' },
    { 'waet', 'wate', 'wayt' },
    { 'wolt' },
    { 'wnt', 'wnta', 'wan' },
    { 'waesh' },
    { 'wlel', 'wull' },
    { 'wnt' },
    { 'wat', 'wot' },
    { 'wil' },
    { 'wit', 'wiv' },
    { 'arf' },
    { 'wrok' },
    { 'yr', 'yaer' },
    { 'yirk' },
    { 'ur', 'yer', 'yur', 'yor' },
    { 'al' },
    { 'nd', 'n' },
    { 'r', 'ar' },
    { 'btat' },
    { 'bedd' },
    { 'bor' },
    { 'caen' },
    { 'kat' },
    { 'dei', 'dy' },
    { 'eg' },
    { 'fer', 'fur', 'four', '4' },
    { 'gya' },
    { 'g' },
    { 'git', 'get' },
    { 'gawd' },
    { 'gawt' },
    { 'gui', 'guy' },
    { 'how', 'hw' },
    { 'im' },
    { 'kdi' },
    { 'lul' },
    { 'mey' },
    { 'nue ' },
    { 'not', 'no' },
    { 'nao', 'naw', 'naow', 'nw' },
    { 'sya' },
    { 'c' },
    { 'sehx', 'seks' },
    { 'smpcb' },
    { 'sap' },
    { 'teh', 'da' },
    { 'too', '2', 'tu', 't', 'tew' },
    { 'wuz' },
    { 'wai', 'y', 'wy' },
    { 'you', 'u', 'yuo', 'yu', 'yuu' },
    { 'dew', 'do' },
    { 'hi' },
    { 'n' },
    { 'es', 'iz' },
    { 'et' },
    { 'meh' },
    { 'mistur' },
    { 'mai', 'mi', 'mah' },
    { 'of', 'uv', 'ef' },
    { 'k' },
    { 'too', '2', 'tu', 't', 'tew' },
    { 'ei', 'i', 'ai' },
}

Fugg.dolan_sub_patterns = {}

function Fugg:init_sub_patterns()
    for i = 1, #Fugg.dolan_patterns do
        Fugg.dolan_sub_patterns[i] = "||" .. i .. "||"
    end
end

